### PR TITLE
Pass config for all components. Fixes #33.

### LINKED ISSUE #33: Theme variables only applied to first diagram
**Describe the bug**
If you defined `themeVariables` to customize colors, fonts, etc., the customizations are only applied to the first diagram in the Markdown document. The second diagram is rendered with the default theme.

**To Reproduce**
1. Setup themes variables:
   ```
    remarkPlugins: [
      [
        require("mdx-mermaid"),
        {
          mermaid: {
            theme: "base",
            themeVariables: {
              primaryColor: "lime",
            },
          },
        },
      ],
    ],
   ```
2. Add two diagrams to a Markdown file:
   ````
   ```mermaid
   graph TD;
        A-->B;
        A-->C;
        B-->D;
        C-->D;
    ```
  
    ```mermaid
    graph TD;
        A-->B;
        A-->C;
        B-->D;
        C-->D;
    ```
   ````
3. Build with `yarn start`
4. See two diagrams with different colors. (see screenshot)

**Expected behavior**
All diagrams should share the same theme configuration.

**Screenshots**
image

**Stack trace**
N/A

**Tool chain used:**
Docusaurus 2.0.0-beta.9, mdx-mermaid 1.2.1

**Additional context**
When experimenting with different colors, you have to CTRL-C to break `yarn start` and then run it again to see the changes.

### PR DESCRIPTION
**Pull request by dprothero**
Opening this PR as it does fix issue #33, however, am I unsure why the code was only passing the config for the first instance in the first place, so some discussion may be required.

### CODE REVIEW

**Comment by sjwall** [comment]
Thank you for the PR, apologies for the delay in reviewing it
Hopefully my comment makes sense, please let me know if you're able to make the changes

**Comment by dprothero** [comment]
I think I understand the issue... the idea with the `first` flag was to try to call initialize only once, but we were actually calling it for every component. The subsequent calls were without the config, which is why we lost the custom styling on subsequent diagrams. I'll take a stab at getting the config working with all instances, but only calling initialize once. Also, it makes sense to only have the single MutationObserver.

**Comment by dprothero** [comment]
@sjwall I got things working following your suggestion. It does work, but feels a little off. The side effect is that you can't use the `<Mermaid>` component by itself without knowing you _must_ pass the `config` attribute to the first (and only the first) instance of the component on a page. This is because we now only call `initialize` if the `config` attribute is set. This means some `<Mermaid>` tests needed to be tweaked.

Anyway, it works for the MDX use case, it just feels a little weird, and I can't help wonder if there's a more elegant way to do this.

**Comment by sjwall** [comment]
The change looks good to me, I agree that it feels a little weird. Something to fix at a later date
There's a small gap in the test coverage

**Comment by sjwall** [comment]
Thank you for the PR, it's released in v1.2.2

**Pull request merged**
